In [1]:
import pandas as pd
import numpy as np
import plotly.express as plx

In [2]:
data = pd.read_csv('drug200.csv')

In [3]:
data

     Age Sex      BP Cholesterol  Na_to_K   Drug
0     23   F    HIGH        HIGH   25.355  DrugY
1     47   M     LOW        HIGH   13.093  drugC
2     47   M     LOW        HIGH   10.114  drugC
3     28   F  NORMAL        HIGH    7.798  drugX
4     61   F     LOW        HIGH   18.043  DrugY
..   ...  ..     ...         ...      ...    ...
195   56   F     LOW        HIGH   11.567  drugC
196   16   M     LOW        HIGH   12.006  drugC
197   52   M  NORMAL        HIGH    9.894  drugX
198   23   M  NORMAL      NORMAL   14.020  drugX
199   40   F     LOW      NORMAL   11.349  drugX

[200 rows x 6 columns]

In [4]:
data.isna().sum()

Age            0
Sex            0
BP             0
Cholesterol    0
Na_to_K        0
Drug           0
dtype: int64

In [5]:
from sklearn.model_selection  import train_test_split

In [6]:
train_in , test_in , train_out , test_out = train_test_split(data[['Age','Sex','BP','Cholesterol','Na_to_K']],data['Drug'] , random_state = 42)

In [7]:
categorical =  train_in.select_dtypes('object').columns.tolist()
categorical

['Sex', 'BP', 'Cholesterol']

In [8]:
from sklearn.preprocessing import OneHotEncoder

In [9]:
encoder = OneHotEncoder(sparse = False , handle_unknown = 'ignore')
encoder.fit(train_in[categorical])
encoder.categories_

C:\Users\DC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

[array(['F', 'M'], dtype=object),
 array(['HIGH', 'LOW', 'NORMAL'], dtype=object),
 array(['HIGH', 'NORMAL'], dtype=object)]

In [10]:
cols_names = list(encoder.get_feature_names_out(categorical))
cols_names

['Sex_F',
 'Sex_M',
 'BP_HIGH',
 'BP_LOW',
 'BP_NORMAL',
 'Cholesterol_HIGH',
 'Cholesterol_NORMAL']

In [11]:
new_train_in = pd.DataFrame()
new_train_in[cols_names] = encoder.transform(train_in[categorical])
new_train_in

,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL
0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,1.0,0.0
4,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...
145,0.0,1.0,0.0,0.0,1.0,1.0,0.0
146,1.0,0.0,0.0,0.0,1.0,1.0,0.0
147,1.0,0.0,1.0,0.0,0.0,1.0,0.0
148,1.0,0.0,0.0,0.0,1.0,1.0,0.0
149,1.0,0.0,0.0,1.0,0.0,1.0,0.0

In [12]:
new_test_in = pd.DataFrame()
encoder.fit(test_in[categorical])
new_test_in[cols_names] = encoder.transform(test_in[categorical])
new_test_in

C:\Users\DC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0
5,0.0,1.0,1.0,0.0,0.0,1.0,0.0
6,1.0,0.0,1.0,0.0,0.0,0.0,1.0
7,1.0,0.0,0.0,0.0,1.0,1.0,0.0
8,0.0,1.0,1.0,0.0,0.0,0.0,1.0
9,1.0,0.0,0.0,0.0,1.0,0.0,1.0
10,0.0,1.0,1.0,0.0,0.0,1.0,0.0
11,1.0,0.0,0.0,1.0,0.0,0.0,1.0
12,0.0,1.0,0.0,1.0,0.0,1.0,0.0
13,1.0,0.0,1.0,0.0,0.0,1.0,0.0
14,0.0,1.0,1.0,0.0,0.0,1.0,0.0
15,0.0,1.0,0.0,0.0,1.0,1.0,0.0
16,0.0,1.0,1.0,0.0,0.0,0.0,1.0
17,0.0,1.0,0.0,0.0,1.0,0.0,1.0
18,1.0,0.0,0.0,1.0,0.0,1.0,0.0
19,0.0,1.0,0.0,0.0,1.0,1.0,0.0
20,1.0,0.0,1.0,0.0,0.0,0.0,1.0
21,0.0,1.0,0.0,1.0,0.0,0.0,1.0
22,1.0,0.0,0.0,1.0,0.0,0.0,1.0
23,1.0,0.0,0.0,1.0,0.0,0.0,1.0
24,1.0,0.0,0.0,0.0,1.0,0.0,1.0
25,1.0,0.0,0.0,1.0,0.0,0.0,1.0
26,1.0,0.0,0.0,1.0,0.0,1.0,0.0
27,0.0,1.0,0.0,0.0,1.0,0.0,1.0
28,1.0,0.0,1.0,0.0,0.0,0.0,1.0
29,0.0,1.0,0.0,1.0,0.0,0.0,1.0
30,0.0,1.0,0.0,1.0,0.0,0.0,1.0
31,0.0,1.0,0.0,1.0,0.0,1.0,0.0
32,1.0,0.0,0.0,1.0,0.0,1.0,0.0
33,0.0,1.0,0.0,1.0,0.0,0.0,1.0
34,0.0,1.0,1.0,0.0,0.0,0.0,1.0
35,0.0,1.0,1.0,0.0,0.0,0.0,1.0
36,0.0,1.0,0.0,1.0,0.0,0.0,1.0
37,1.0,0.0,1.0,0.0,0.0,1.0,0.0
38,0.0,1.0,1.0,0.0,0.0,0.0,1.0
39,1.0,0.0,1.0,0.0,0.0,1.0,0.0
40,1.0,0.0,0.0,1.0,0.0,0.0,1.0
41,0.0,1.0,0.0,0.0,1.0,1.0,0.0
42,1.0,0.0,0.0,0.0,1.0,0.0,1.0
43,1.0,0.0,0.0,1.0,0.0,1.0,0.0
44,0.0,1.0,0.0,0.0,1.0,1.0,0.0
45,1.0,0.0,0.0,1.0,0.0,1.0,0.0
46,0.0,1.0,0.0,1.0,0.0,1.0,0.0
47,1.0,0.0,1.0,0.0,0.0,0.0,1.0
48,0.0,1.0,1.0,0.0,0.0,0.0,1.0
49,1.0,0.0,0.0,0.0,1.0,1.0,0.0

In [13]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
numeric = train_in.select_dtypes(include = np.number).columns.tolist()
scaler.fit(train_in[numeric])
new_train_in[numeric] = scaler.transform(train_in[numeric])

In [14]:
new_test_in[numeric] = scaler.fit_transform(test_in[numeric])
new_test_in

,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL,Age,Na_to_K
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-0.295561,-0.626167
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.482552,-0.057806
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.363853,-0.997575
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.069479,-0.762285
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.357284,2.445931
5,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.594683,0.328186
6,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.363853,1.158922
7,1.0,0.0,0.0,0.0,1.0,1.0,0.0,-0.770357,-0.424074
8,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.060537,-0.439769
9,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.484926,-1.086885
10,0.0,1.0,1.0,0.0,0.0,1.0,0.0,-0.711008,-0.427269
11,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-1.245154,-0.589777
12,0.0,1.0,0.0,1.0,0.0,1.0,0.0,-0.176862,0.328186
13,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.304504,-0.363793
14,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.722325,-0.844928
15,0.0,1.0,0.0,0.0,1.0,1.0,0.0,-0.948406,0.427635
16,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.425577,-0.637835
17,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.832081,-1.204391
18,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.532959,-0.863957
19,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.772731,1.211980
20,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.713382,-0.477410
21,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.662975,-0.621862
22,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.188178,-1.193418
23,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.060537,1.852707
24,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.603626,1.544219
25,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.176862,1.936600
26,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.357284,-0.814649
27,0.0,1.0,0.0,0.0,1.0,0.0,1.0,-1.423203,-0.708394
28,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.304504,1.394073
29,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.475984,-0.324208
30,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.119886,0.477221
31,0.0,1.0,0.0,1.0,0.0,1.0,0.0,-1.067105,-1.199252
32,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.889057,-0.246148
33,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-0.889057,0.691260
34,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.475984,-1.004520
35,0.0,1.0,1.0,0.0,0.0,0.0,1.0,-1.126455,1.717005
36,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.959723,-0.554636
37,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.354910,-0.421991
38,0.0,1.0,1.0,0.0,0.0,0.0,1.0,-1.482552,0.427080
39,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.295561,-0.657558
40,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.532959,-0.707283
41,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.654032,-0.838678
42,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.117512,-0.864374
43,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.473610,2.438153
44,0.0,1.0,0.0,0.0,1.0,1.0,0.0,-0.414260,0.906131
45,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.891431,-0.606305
46,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.238585,0.280406
47,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.532959,1.394767
48,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.959723,-0.068917
49,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.594683,-0.324347

In [15]:
new_train_in

,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL,Age,Na_to_K
0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.566235,-0.951024
1,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.272674,0.361268
2,1.0,0.0,0.0,0.0,1.0,1.0,0.0,-1.443039,-1.044541
3,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.267279,0.029380
4,1.0,0.0,0.0,0.0,1.0,1.0,0.0,-0.334272,-0.836972
...,...,...,...,...,...,...,...,...,...
145,0.0,1.0,0.0,0.0,1.0,1.0,0.0,-1.443039,-0.580285
146,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.281709,-0.476223
147,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.011852,1.847414
148,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.328877,-0.033890
149,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-1.073450,-0.417394

In [16]:
new_train_in.describe()

,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL,Age,Na_to_K
count,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,1.500000e+02,1.500000e+02
mean,0.473333,0.526667,0.400000,0.286667,0.313333,0.546667,0.453333,-1.835569e-16,-1.883678e-16
std,0.500961,0.500961,0.491539,0.453719,0.465403,0.499485,0.499485,1.003350e+00,1.003350e+00
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.874225e+00,-1.368937e+00
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-8.270574e-01,-7.896931e-01
50%,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,6.611531e-02,-2.856509e-01
75%,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,8.360918e-01,4.484378e-01
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.760063e+00,3.067993e+00

In [17]:
len(numeric)
new_train_in
encoder.categories_

[array(['F', 'M'], dtype=object),
 array(['HIGH', 'LOW', 'NORMAL'], dtype=object),
 array(['HIGH', 'NORMAL'], dtype=object)]

In [18]:
from sklearn.feature_selection import chi2

# Prepare data (X: features, y: target variable)
X = new_train_in[cols_names]
y = train_out 
# Compute Chi-square statistics and p-values
chi2_stats, p_values = chi2(X, y)


# Get indices of top K features based on chi2 statistics
top_k_features = chi2_stats.argsort()[-3:]

# Print selected features
print(f"Top {4} features based on Chi-square:")
for i in top_k_features:
    print(f"- Feature {i}" , train_in.columns[i])

Top 4 features based on Chi-square:
- Feature 3 Cholesterol
- Feature 4 Na_to_K
- Feature 2 BP

In [19]:
from sklearn.datasets import load_iris
from sklearn.feature_selection import f_classif

# Load the iris dataset

X = new_train_in[numeric]
y = train_out

# Compute the ANOVA F-value and p-value for each feature
f_values, p_values = f_classif(X, y)

# Print the F-value and p-value for each feature
for i in range(X.shape[1]):
    print("Feature %d: F-value=%.2f, p-value=%.2f" % (i, f_values[i], p_values[i]))

Feature 0: F-value=5.68, p-value=0.00
Feature 1: F-value=57.21, p-value=0.00

In [20]:
from sklearn.svm import SVC
model=SVC()

In [22]:
model.fit(new_train_in, train_out)

SVC()

In [29]:
pred=model.predict(new_test_in)

In [30]:
from sklearn.metrics import classification_report , confusion_matrix

In [33]:
print(classification_report(test_out, pred))

              precision    recall  f1-score   support

       DrugY       0.90      0.95      0.93        20
       drugA       1.00      1.00      1.00         6
       drugB       0.75      1.00      0.86         3
       drugC       1.00      0.67      0.80         6
       drugX       1.00      1.00      1.00        15

    accuracy                           0.94        50
   macro avg       0.93      0.92      0.92        50
weighted avg       0.95      0.94      0.94        50

In [34]:
con_mat = confusion_matrix(test_out , pred )

In [35]:
con_mat

array([[19,  0,  1,  0,  0],
       [ 0,  6,  0,  0,  0],
       [ 0,  0,  3,  0,  0],
       [ 2,  0,  0,  4,  0],
       [ 0,  0,  0,  0, 15]], dtype=int64)

In [102]:
print(model.predict([[1.0,0.0,1.0,0.0,0.0,0.0,1.0, -0.272674,0.361268]]))
print(train_out.iloc[1])

['DrugY']
DrugY

C:\Users\DC\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [55]:
new_train_in = new_train_in.drop( 'Na_to_K' , axis  =1)
new_test_in = new_test_in.drop( 'Na_to_K' , axis  =1)

In [57]:
new_test_in

,Sex_F,Sex_M,BP_HIGH,BP_LOW,BP_NORMAL,Cholesterol_HIGH,Cholesterol_NORMAL,Age
0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-0.295561
1,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.482552
2,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-1.363853
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.069479
4,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.357284
5,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.594683
6,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.363853
7,1.0,0.0,0.0,0.0,1.0,1.0,0.0,-0.770357
8,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.060537
9,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.484926
10,0.0,1.0,1.0,0.0,0.0,1.0,0.0,-0.711008
11,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-1.245154
12,0.0,1.0,0.0,1.0,0.0,1.0,0.0,-0.176862
13,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-1.304504
14,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.722325
15,0.0,1.0,0.0,0.0,1.0,1.0,0.0,-0.948406
16,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.425577
17,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.832081
18,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.532959
19,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.772731
20,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.713382
21,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.662975
22,1.0,0.0,0.0,1.0,0.0,0.0,1.0,1.188178
23,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.060537
24,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.603626
25,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.176862
26,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.357284
27,0.0,1.0,0.0,0.0,1.0,0.0,1.0,-1.423203
28,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-1.304504
29,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.475984
30,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.119886
31,0.0,1.0,0.0,1.0,0.0,1.0,0.0,-1.067105
32,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.889057
33,0.0,1.0,0.0,1.0,0.0,0.0,1.0,-0.889057
34,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.475984
35,0.0,1.0,1.0,0.0,0.0,0.0,1.0,-1.126455
36,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.959723
37,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.354910
38,0.0,1.0,1.0,0.0,0.0,0.0,1.0,-1.482552
39,1.0,0.0,1.0,0.0,0.0,1.0,0.0,-0.295561
40,1.0,0.0,0.0,1.0,0.0,0.0,1.0,-0.532959
41,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.654032
42,1.0,0.0,0.0,0.0,1.0,0.0,1.0,-0.117512
43,1.0,0.0,0.0,1.0,0.0,1.0,0.0,-0.473610
44,0.0,1.0,0.0,0.0,1.0,1.0,0.0,-0.414260
45,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.891431
46,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.238585
47,1.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.532959
48,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.959723
49,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.594683

In [62]:
model.fit(new_train_in , train_out)
predict_value = model.predict(new_test_in)

In [63]:
classification_report = classification_report(predict_value , test_out)

In [65]:
print(classification_report)

              precision    recall  f1-score   support

       DrugY       0.60      0.38      0.46        32
       drugA       0.17      0.33      0.22         3
       drugB       0.67      0.67      0.67         3
       drugC       0.17      0.50      0.25         2
       drugX       0.40      0.60      0.48        10

    accuracy                           0.44        50
   macro avg       0.40      0.49      0.42        50
weighted avg       0.52      0.44      0.45        50

In [66]:
con_mat = confusion_matrix(predict_value , test_out)
print(con_mat)

[[12  5  1  5  9]
 [ 2  1  0  0  0]
 [ 1  0  2  0  0]
 [ 1  0  0  1  0]
 [ 4  0  0  0  6]]